version: '3.4'

networks:
  dev:
    driver: bridge 

services:
  minimalmeet-api:
   image: minimalmeet
   container_name: minimalmeet
   depends_on:
     - database
   build:
     context: ./
   environment:
     - ASPNETCORE_ENVIRONMENT=docker
   ports:
    - 8088:8088
   networks:
     - dev

  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - dev