version: "3.4"

services:
  minimalmeet-js:
    container_name: minimalmeet-js
    build:
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: ${PORT}
      DB_USER: ${USER}
      DB_PASSWORD: ${PASSWORD}
    ports:
      - 13000:3000
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_PORT: ${PORT}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_USER: ${USER}
    ports:
      - 5432:5432
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
